config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "tables#index"

  mount GoodJob::Engine => 'good_job'

  resources :tables do
    get 'refresh', on: :member
    get 'refresh_all', on: :collection

    resources :table_rows
  end

  resources :clubs do
    get 'refresh', on: :member
    get 'refresh_all', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/club.rb
class Club < ApplicationRecord
	has_many :table_rows
	has_many :tables, through: :table_rows
	has_many :matches
	has_one :elo

	validates :name, presence: true, length: { maximum: 100 }
	validates :location, presence: true, length: { maximum: 100 }
	validates :country_abbr, presence: true, length: { minimum: 2, maximum: 2 }
	validates :config, presence: true
	validates :gender, presence: true, inclusion: { in: %w(women's men's), message: "%{value} is not a valid league gender" }
	validates :club_or_international, presence: true, inclusion: { in: %w(club international), message: "%{value} is not a valid value" }
end

app/models/elo.rb
class Elo < ApplicationRecord
  belongs_to :club, optional: true

  validates :club_name, presence: true
  validates :elo_rating, presence: true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :table, optional: true
  belongs_to :home_team, :class_name => 'Club', optional: true
  belongs_to :away_team, :class_name => 'Club', optional: true

  validates :date_time, presence: true
  validates :round, presence: true, length: { maximum: 40 }
  validates :home_team_name, presence: true, length: { maximum: 100 }
  validates :away_team_name, presence: true, length: { maximum: 100 }
  validates :neutral_site, inclusion: [true, false]
end

app/models/table.rb
class Table < ApplicationRecord
	has_many :table_rows
	has_many :clubs, through: :table_rows
	has_many :matches

	validates :country_abbr, presence: true, length: { minimum: 2, maximum: 2 }
 	validates :level, presence: true, numericality: { only_integer: true }
 	validates :name, presence: true, length: { maximum: 100 }
	validates :config, presence: true
	validates :gender, presence: true, inclusion: { in: %w(women's men's), message: "%{value} is not a valid league gender" }
	validates :club_or_international, presence: true, inclusion: { in: %w(club international), message: "%{value} is not a valid value" }
end

app/models/table_row.rb
class TableRow < ApplicationRecord
  belongs_to :table
  belongs_to :club, optional: true

  validates_associated :table

  def elo_rating
    club&.elo&.elo_rating
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clubs_controller.rb
require 'json'

class ClubsController < ApplicationController
  def index
    @clubs = Club.all
  end

  def show
    @club = Club.find(params[:id])

    @table_snippets = club_service.generate_table_snippets(@club)

    @matches = club_service.find_matches(@club)
  end

  def new
    @club = Club.new
  end

  def create
    @club = Club.new(table_params)

    if @club.save
      club_service.associate_club(@club)
      redirect_to @club
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @club = Club.find(params[:id])
  end

  def update
    @club = Club.find(params[:id])

    if @club.update(table_params)
      club_service.associate_club(@club)
      redirect_to @club
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def refresh
    @club = Club.find(params[:id])

    if club_service.refresh_club(params[:id])
      sleep(2.0)
      redirect_to @club
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def refresh_all
    if club_service.refresh_all_clubs
      sleep(2.0)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @club = Club.find(params[:id])
    @club.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def table_params
    raw_params = params.require(:club).permit(:name, :short_name, :location, :country_abbr, :gender, :club_or_international, :fbref_table_name, :fbref_club_page_name, :fbref_url, :club_elo_name)
    params_with_config = raw_params

    # will likely end up refactoring this to handle multiple additional fields at some point
    params_with_config[:config] = {
      fbref_table_name: raw_params[:fbref_table_name],
      fbref_club_page_name: raw_params[:fbref_club_page_name],
      fbref_url: raw_params[:fbref_url],
      club_elo_name: raw_params[:club_elo_name]
    }
    params_with_config.except(:fbref_table_name, :fbref_club_page_name, :fbref_url, :club_elo_name)
  end

  def club_service
    ClubService.new
  end
end

app/controllers/table_rows_controller.rb
class TableRowsController < ApplicationController
end

app/controllers/tables_controller.rb
require 'json'

class TablesController < ApplicationController
  def index
    @tables = Table.all
  end

  def show
    @table = Table.find(params[:id])

    # sorting code mostly from https://code.avi.nyc/turbo-sortable-paginated-tables
    sort_column = params[:sort] || "position"
    sort_direction = params[:direction].presence_in(%w[asc desc]) || "asc"

    if %w[position team_name points goal_difference xg_diff_per90].include?(sort_column)
      @table_rows = @table.table_rows.order("#{sort_column} #{sort_direction}")
    else
      # works for integer sort - necessary if avoiding db sort
      @table_rows = @table.table_rows.all.sort_by do |row|
        row.send(sort_column.to_sym) || 0
      end

      @table_rows.reverse! if sort_direction == "desc"
    end
  end

  def new
    @table = Table.new
  end

  def create
    @table = Table.new(table_params)

    if @table.save
      redirect_to @table
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @table = Table.find(params[:id])
  end

  def update
    @table = Table.find(params[:id])

    if @table.update(table_params)
      redirect_to @table
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def refresh
    @table = Table.find(params[:id])

    if table_refresh_service.refresh_table(params[:id])
      sleep(1.0)
      redirect_to @table
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def refresh_all
    if table_refresh_service.refresh_all_tables
      sleep(1.0)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def table_params
    raw_params = params.require(:table).permit(:country_abbr, :level, :name, :gender, :club_or_international, :fbref_table_name, :fbref_url)
    params_with_config = raw_params

    # will likely end up refactoring this to handle multiple additional fields at some point
    params_with_config[:config] = {
      fbref_table_name: raw_params[:fbref_table_name],
      fbref_url: raw_params[:fbref_url]
    }
    params_with_config.except(:fbref_table_name, :fbref_url)
  end

  def table_refresh_service
    TableRefreshService.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable_table_header(title, column, path_method, **)
    content_tag(:th, class: "table__th") do
      sortable_column(title, column, path_method)
    end
  end

  def sortable_column(title, column, path_method, **)
    direction = (column.to_s == params[:sort].to_s && params[:direction] == "asc") ? "desc" : "asc"

    query_params = request.query_parameters.merge(sort: column, direction: direction)

    path = send(path_method, query_params)
    link_to(path, class: "flex items-center", **) do
      concat title
      concat sort_icon(column)
    end
  end

  def sort_icon(column)
    return unless params[:sort].to_s == column.to_s

    if params[:direction] == "asc"
      svg_icon("M5 15l7-7 7 7")
    else
      svg_icon("M19 9l-7 7-7-7")
    end
  end

  def svg_icon(path_d)
    content_tag(:svg, xmlns: "http://www.w3.org/2000/svg", class: "ml-1 inline w-4 h-4", width: "10", height: "10", fill: "none", viewBox: "0 0 24 24", stroke: "currentColor") do
      "<path stroke-linecap='round' stroke-linejoin='round' stroke-width='2' d='#{path_d}'></path>".html_safe
    end
  end
end

app/helpers/table_rows_helper.rb
module TableRowsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/clubs/_form.html.erb
<%= form_with model: club do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
    <% club.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :short_name %><br>
    <%= form.text_area :short_name %>
    <% club.errors.full_messages_for(:short_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :country_abbr %><br>
    <%= form.text_field :country_abbr %>
    <% club.errors.full_messages_for(:country_abbr).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :location %><br>
    <%= form.text_area :location %>
    <% club.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :gender %><br>
    <%= form.text_area :gender %>
    <% club.errors.full_messages_for(:gender).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :club_or_international %><br>
    <%= form.text_area :club_or_international %>
    <% club.errors.full_messages_for(:club_or_international).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <% @club.config.keys.each do |key| %>
    <div class="field">
      <%= form.label key %><br />
      <%= text_area_tag "club[" + key + "]", @club.config[key], size: "20x5" %>
    </div>
  <% end %>

<% if !@club.config.keys.include?("fbref_table_name") %>
  <div>
    <%= form.label :fbref_table_name %><br>
    <%= form.text_area :fbref_table_name %>
    <% club.errors.full_messages_for(:fbref_table_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>
<% if !@club.config.keys.include?("fbref_club_page_name") %>
  <div>
    <%= form.label :fbref_club_page_name %><br>
    <%= form.text_area :fbref_club_page_name %>
    <% club.errors.full_messages_for(:fbref_club_page_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>
<% if !@club.config.keys.include?("fbref_url") %>
  <div>
    <%= form.label :fbref_url %><br>
    <%= form.text_area :fbref_url %>
    <% club.errors.full_messages_for(:fbref_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>
<% if !@club.config.keys.include?("club_elo_name") %>
  <div>
    <%= form.label :club_elo_name %><br>
    <%= form.text_area :club_elo_name %>
    <% club.errors.full_messages_for(:club_elo_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Edit Club</h1>

<%= render "form", club: @club %>

app/views/clubs/index.html.erb
<h1>Clubs</h1>

<ul>
  <% @clubs.each do |club| %>
    <li>
      <%= link_to club.name, club %>
    </li>
  <% end %>
</ul>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render "form", club: @club %>

app/views/clubs/show.html.erb
<%= turbo_include_tags %>
<h1><%= @club.name %></h1>

<p><%= @club.location %></p>

<% if @club.elo %>
<p>ELO rating: <%= @club.elo.elo_rating %></p>
<% end %>

<% @table_snippets.each do |table_snippet| %>
 <h3><%= link_to table_snippet[:table][:name], table_snippet[:table] %></h3>
 <table class="table sortable">
  <thead class="table__thead">
    <%= render "table_rows/unsortable_table_header" %>
  </thead>
  <tbody>
    <%= render table_snippet[:table_rows] %>
  </tbody>
</table>
<% end %>

<h3>Matches</h3>
<table class="table sortable">
  <thead class="table__thead">
    <%= render "matches/unsortable_table_header" %>
  </thead>
  <tbody>
    <%= render @matches %>
  </tbody>
</table>

<ul data-turbo-prefetch="false">
  <li><%= link_to "Back to tables", tables_path %></li>
  <li><%= link_to "New Club", new_club_path %></li>
  <li><%= link_to "Refresh", refresh_club_path(@club) %></li>
  <li><%= link_to "Edit", edit_club_path(@club) %></li>
  <li><%= link_to "Destroy", club_path(@club), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<style>
td, th {
  border: 1px solid #999;
  background-color: #AFEEEE;
}
td {
  padding: 0.3rem;
}
th {
  padding: 0.9rem;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rta</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matches/_match.html.erb
<tr>
    <td><%= match.date_time %></td>
    <td><%= link_to_if(match.table.present?, match.competition_name, match.table)  %></td>
    <td><%= match.round %></td>
    <% if match.home_team.present? %>
        <td><%= link_to_if(match.home_team.present?, match.home_team.short_name || match.home_team_name, match.home_team)  %></td>
    <% else %>
        <td><%= link_to_if(match.home_team.present?, match.home_team_name, match.home_team)  %></td>
    <% end %>
    <% if match.away_team.present? %>
        <td><%= link_to_if(match.away_team.present?, match.away_team.short_name || match.away_team_name, match.away_team)  %></td>
    <% else %>
        <td><%= link_to_if(match.away_team.present?, match.away_team_name, match.away_team)  %></td>
    <% end %>
    <% if !match.home_penalties %>
        <td><%= match.home_goals %></td>
        <td><%= match.away_goals %></td>
    <% else %>
        <td><%= match.home_goals %> (<%= match.home_penalties %>)</td>
        <td><%= match.away_goals %> (<%= match.away_penalties %>)</td>
    <% end %>
    <td><%= match.home_xg %></td>
    <td><%= match.away_xg %></td>
    <td><%= match.attendance %></td>
 </tr>

app/views/matches/_unsortable_table_header.html.erb
<tr>
  <th class="table__row--header">Date</th>
  <th class="table__row--header">Competition</th>
  <th class="table__row--header">Round</th>
  <th class="table__row--header">Home Team</th>
  <th class="table__row--header">Away Team</th>
  <th class="table__row--header">Home Goals</th>
  <th class="table__row--header">Away Goals</th>
  <th class="table__row--header">Home xG</th>
  <th class="table__row--header">Away xG</th>
  <th class="table__row--header">Attendance</th>
</tr>

app/views/table_rows/_sortable_table_header.html.erb
<tr>
  <%= sortable_table_header 'Position', :position, :table_path, class: 'table__row--header' %>
  <%= sortable_table_header 'Team Name', :team_name, :table_path, class: 'table__row--header' %>
  <%= sortable_table_header 'Points', :points, :table_path, class: 'table__row--header' %>
  <%= sortable_table_header 'Goal Difference', :goal_difference, :table_path, class: 'table__row--header' %>
  <%= sortable_table_header 'xG Difference per 90', :xg_diff_per90, :table_path, class: 'table__row--header' %>
  <%= sortable_table_header 'ELO Rating', :elo_rating, :table_path, class: 'table__row--header' %>
</tr>

app/views/table_rows/_table_row.html.erb
<tr>
    <td class="position"><%= table_row.position %></td>
    <td><%= link_to_if(table_row.club.present?, table_row.team_name, table_row.club)  %></td>
    <td><%= table_row.points%></td>
    <td><%= table_row.goal_difference %></td>
    <td><%= table_row.xg_diff_per90 %></td>
    <td><%= table_row.club&.elo&.elo_rating %></td>
 </tr>

app/views/table_rows/_unsortable_table_header.html.erb
<tr>
  <th class="table__row--header">Position</th>
  <th class="table__row--header">Team Name</th>
  <th class="table__row--header">Points</th>
  <th class="table__row--header">Goal Difference</th>
  <th class="table__row--header">xG Difference per 90</th>
  <th class="table__row--header">ELO Rating</th>
</tr>

app/views/tables/_form.html.erb
<%= form_with model: table do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_area :name %>
    <% table.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :country_abbr %><br>
    <%= form.text_field :country_abbr %>
    <% table.errors.full_messages_for(:country_abbr).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :level %><br>
    <%= form.text_area :level %>
    <% table.errors.full_messages_for(:level).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :gender %><br>
    <%= form.text_area :gender %>
    <% table.errors.full_messages_for(:gender).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :club_or_international %><br>
    <%= form.text_area :club_or_international %>
    <% table.errors.full_messages_for(:club_or_international).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

<% @table.config.keys.each do |key| %>
  <div class="field">
    <%= form.label key %><br />
    <%= text_area_tag "table[" + key + "]", @table.config[key], size: "20x5" %>
  </div>
<% end %>

<% if !@table.config.keys.include?("fbref_table_name") %>
  <div>
    <%= form.label :fbref_table_name %><br>
    <%= form.text_area :fbref_table_name %>
    <% table.errors.full_messages_for(:fbref_table_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>
<% if !@table.config.keys.include?("fbref_url") %>
  <div>
    <%= form.label :fbref_url %><br>
    <%= form.text_area :fbref_url %>
    <% table.errors.full_messages_for(:fbref_url).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
<% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Edit Table</h1>

<%= render "form", table: @table %>

app/views/tables/index.html.erb
<h1>Tables</h1>

<ul>
  <% @tables.each do |table| %>
    <li>
      <%= link_to table.name, table %>
    </li>
  <% end %>
</ul>

<br><br>
<h5>Setup options</h5>
<ul data-turbo-prefetch="false">
  <li><%= link_to "New table", new_table_path %></li>
  <li><%= link_to "New club", new_club_path %></li>
  <li><%= link_to "Refresh all tables", refresh_all_tables_path %></li>
  <li><%= link_to "Refresh all clubs", refresh_all_clubs_path %></li>
</ul>

app/views/tables/new.html.erb
<h1>New Table</h1>

<%= render "form", table: @table %>

app/views/tables/show.html.erb
<%= turbo_include_tags %>
<h1><%= @table.name %></h1>

<p><%= @table.country_abbr %>, level <%= @table.level %></p>

<table class="table sortable">
  <thead class="table__thead">
    <%= render "table_rows/sortable_table_header" %>
  </thead>
  <tbody>
    <%= render @table_rows %>
  </tbody>
</table>

<ul data-turbo-prefetch="false">
  <li><%= link_to "Back to tables", tables_path %></li>
  <li><%= link_to "Refresh", refresh_table_path(@table) %></li>
  <li><%= link_to "Edit", edit_table_path(@table) %></li>
  <li><%= link_to "New club", new_club_path %></li>
  <li><%= link_to "Destroy", table_path(@table), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<style>
td, th {
  border: 1px solid #999;
}
td {
  padding: 0.3rem;
}
th {
  padding: 0.9rem;
}
<%# generated with https://colordesigner.io/gradient-generator %>
tr.position-1 {
  background-color: #77e094;
}
tr.position-2 {
  background-color: #8ae39c;
}
tr.position-3 {
  background-color: #9ce6a4;
}
tr.position-4 {
  background-color: #ace9ad;
}
tr.position-5 {
  background-color: #bbecb7;
}
tr.position-6 {
  background-color: #c9efc2;
}
tr.position-7 {
  background-color: #d6f2cd;
}
tr.position-8 {
  background-color: #e2f5d9;
}
tr.position-9 {
  background-color: #edf9e6;
}
tr.position-10 {
  background-color: #f7fcf3;
}
tr.position-11 {
  background-color: #f7fcf3;
}
tr.position-12 {
  background-color: #ebf0de;
}
tr.position-13 {
  background-color: #e3e3c8;
}
tr.position-14 {
  background-color: #ded6b3;
}
tr.position-15 {
  background-color: #dbc79f;
}
tr.position-16 {
  background-color: #dbb78e;
}
tr.position-17 {
  background-color: #daa680;
}
tr.position-18 {
  background-color: #da9577;
}
tr.position-19 {
  background-color: #d98371;
}
tr.position-20 {
  background-color: #d77070;
}
</style>

<script>

  // Select all tr elements
  var rows = document.querySelectorAll("tr");

  // Loop through each tr element
  for(let i = 1; i < rows.length; i++){

    // Get the position value of the current product
    let position = rows[i].querySelector(".position").textContent;

    // Add a class to the current element based on position value
    rows[i].classList.add(`position-${position}`);
  }

</script>